### ISSUE TITLE
`Some` fails on large probabilities

### ISSUE THREAD

**Issue by OliveIsAWord** [CoffeeVCV/CoffeeVCV#3] opened 2022-05-16 22:37 UTC
For any probability `p` where `(num_inputs - 1) / num_inputs < p < 1`, the Some module will never mute the bottom-most input. [Here is a patch which demonstrates this behavior.](https://github.com/CoffeeVCV/CoffeeVCV/files/8703805/Some_module_bug.zip)

![image](https://user-images.githubusercontent.com/89336634/168693506-327e46c4-18ec-4deb-9e50-e173ff72c4d4.png)

**Comment by OliveIsAWord** [comment] 2022-05-17 02:05
I've tracked the bug to an off-by-one error in [this line of code](https://github.com/CoffeeVCV/CoffeeVCV/blob/master/src/Some.cpp#L62). `(sigs.size()-1)` should be replaced with `sigs.size()`. Alternatively, `std::shuffle` or similar could be used instead. Currently, the second index will never reach the last element, so that last element will only be swapped at the last step of the loop. It's guaranteed to be moved forward since the two indexes will not be equal at that last step.

The code also has some other issues. Notably, the formatting is inconsistent and there is a heap allocation. This warrants revisions in the future.

**Comment by CoffeeVCV** [comment] 2022-05-18 06:07
Hello, thank you for taking the time to report and investigate this issue.
This projects is my first time using cpp and also vectors, and I'm very happy to receive feedback.
I used sigs.size-1, and that should return 7, the array is indexed 0 - 7.   
I think the problem is that 7*0.99 is 6.93 and when cast as an index, results in sigs[6].
so I think round((sigs.size-1)*random::uniform) might be better.

**Comment by CoffeeVCV** [comment] 2022-05-18 09:08
Your suggestion works well, it will be in the next update.
I did look at std:shuffle, but I'm not familiar enough with the std that VCV uses, could not figure out how to make it work.

**Comment by OliveIsAWord** [comment] 2022-05-19 00:33
Using `round` will bias against the first and last index. `rack::random::shuffle` is guaranteed to return a value in `[0, 1)` so `sigs.size()*random::uniform()` will never return a value `sigs.size()` or greater. And yes, I also have no clue how VCV Rack's built-in random library would work with C++'s stdlib.

**Comment by OliveIsAWord** [comment] 2022-05-20 10:18
I'm working on a pull request that identifies this issue as well as others I identified in my search. The maintainer is of course free to dismiss any of these, and I'd be happy to explain any revisions that aren't clearly beneficial.

**Closed as completed** 2022-05-22 07:41 UTC
